---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# cvr_harvard-mit_scripts

##### Project leads: Shiro Kuriwaki and Mason Reece

<!-- badges: start -->
<!-- badges: end -->

The goal of `cvr_harvard-mit_scripts` is to coordinate the "Harvard" and "MIT" team's CVR data. We track/resolve issues in each county and state and write scripts to fix and merge our raw data. A convenient way to update the status indicators is to run the file `update_counbined-release.sh` in shell.

The github repo is kept for _issue tracking purposes_ and _maintaining data construction scripts_ only.

There should be no data stored in this repo.  Metadata required for scripts are in a `metadata` subfolder nested in the `R` directory. See the shared Dropbox `CVR_parquet` for subsets of cleaned in parquet format. 

We will be releasing MIT's version of the script in the Dataverse / paper. 

