---
title: "CVR Overlap: By District"
author: "Shiro Kuriwaki"
date: today
format: 
  html:
    self-contained: true
execute:
  echo: false
---

```{r}
#| include: false
suppressPackageStartupMessages({
  library(tidyverse)
  library(here)
  library(gt)
})
```


# Differences in US House District Counts

This is showing each team's counts of CVRs for which: 

* district is coded as a number ("005" or "5), and
* candidate's party is coded exactly as "REPUBLICAN" or "DEMOCART".

So if a district value is NA, it may just be because the district is not coded as a number, or partisanship of the candidate was not recorded.

```{r}
comp_tbl_ush <- read_csv(here("data/tmp_ushou_harv-medsl.csv"), show_col_types = FALSE)

comp_tbl_ush |>
  gt() |>
  sub_missing() |>
  tab_spanner("MEDSL", columns = matches("_medsl")) |>
  tab_spanner("Harvard", columns = matches("_harv")) |>
  cols_label(N_REP_medsl = "R (MIT)",
             N_DEM_medsl = "D (MIT)",
             N_REP_harv = "R (Harv)",
             N_DEM_harv = "D (Harv)") |>
  fmt_integer() |>
  opt_interactive(use_filters = TRUE)
```

